apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "helsearbeidsgiver-wonderwall-demo"
  namespace: "helsearbeidsgiver"
  labels:
    team: "helsearbeidsgiver"
spec:
  image: {{image}}
  liveness:
    path: "/api/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200"
      memory: "256Mi"
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
      locale: nb
